# Generated by Django 5.2.7 on 2025-10-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_add_llr_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupconstraintclass',
            options={'verbose_name': 'Clase en Restricción de Grupo', 'verbose_name_plural': 'Clases en Restricciones de Grupo'},
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_demands', to='schedule_app.course'),
        ),
    ]
