# Generated by Django 5.2.7 on 2025-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_groupconstraintclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='completed', max_length=20),
        ),
    ]
