# Generated by Django 5.2.7 on 2025-11-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='conflict_count',
            field=models.IntegerField(default=0),
        ),
    ]
