# Generated by Django 5.2.7 on 2025-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_schedule_conflict_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='classes_assigned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classes_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dataset',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='generation_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
